# frozen_string_literal: true
source "https://rubygems.org"

ruby ">= 3.0.3"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
#gem "thin"
gem "sinatra-contrib"

# CORS support
# Disabled the first one as I had to write code for OPTIONS
# If any issues revert to the previous one
# gem "sinatra-cross_origin", "~> 0.3.1"
#gem 'sinatra-cors', '~> 1.2'
gem 'sinatra-cors'

# gem "google-api-client"
gem "fileutils"


gem 'google-apis-core', '~> 1.0', '>= 1.0.2'
gem 'google-apis-sheets_v4', '~> 0.45.0'
gem 'googleauth', '~> 1.15', '>= 1.15.1'
gem 'faraday'

#gem "rackup", "~> 2.2"
#gem "puma", "~> 7.1"
gem "rackup"
gem "puma"
